debug: true
transporter:
  redis:
    host: localhost
    port: 6379
    username:
    password:
    db: 0
  p2p:
database:
  leveldb:
    main:
      path: /var/block-node-example/data/main.db
    discovery:
      path: /var/block-node-example/data/discovery.db
storage:
  type: ""
