debug: true
transporter:
  redis:
    host: localhost
    port: 6379
    username:
    password:
    db: 0
  p2p:
database:
  leveldb:
    main:
      path: /Users/mac/go/src/gitlab.com/blockapi/auth-service/build/data/main.db
    discovery:
      path: /Users/mac/go/src/gitlab.com/blockapi/auth-service/build/data/discovery.db
#   couch_db:
#     host: 127.0.0.1
#     port: 5984
#     username: admin
#     password: admin
#     prefix: "bn_"
storage:
  type: ""
