debug: true
transport:
  redis:
    host: localhost
    port: 6379
    username:
    password:
    db: 0
  p2p:
# database:
#   couch_db:
#     host: 127.0.0.1
#     port: 5984
#     username: admin
#     password: admin
#     prefix: "auth_"
