debug: false
transporter:
  timeout: 30 # default timeout for actions, in seconds
  heartbeatInterval: 5 # in seconds
  deliveryMethod: random
  redis:
    host: redis
    port: 6379
    username:
    password:
    db: 0
  p2p:
database:
  leveldb:
    discovery:
      path: /var/block-node/ping-pong-service/data/discovery.db
