debug: false
transporter:
  redis:
    host: redis
    port: 6379
    username:
    password:
    db: 0
  p2p:
database:
  leveldb:
    discovery:
      path: /var/block-node/ping-pong-service/data/discovery.db
