debug: false
transporter:
  redis:
    host: localhost
    port: 6379
    username:
    password:
    db: 0
  p2p:
database:
  leveldb:
    discovery:
      path: /var/block-node-example/data/db-discovery
